package model

// Country is generated type for table 'countries'
type Country struct {
	Code          int    `db:"code" json:"code" mapstructure:"code"`
	Name          string `db:"name" json:"name" mapstructure:"name"`
	ContinentName string `db:"continent_name" json:"continent_name" mapstructure:"continent_name"`
}

// table 'countries' columns list struct
type __tbl_countries_columns struct {
	Code          string
	Name          string
	ContinentName string
}

// table 'countries' metadata struct
type __tbl_countries struct {
	Name    string
	Columns __tbl_countries_columns
}

// table 'countries' metadata info
var _tbl_countries = __tbl_countries{
	Columns: __tbl_countries_columns{
		Code:          "code",
		ContinentName: "continent_name",
		Name:          "name",
	},
	Name: "countries",
}

// GetColumns return list columns name for table 'countries'
func (*__tbl_countries) GetColumns() []string {
	return []string{"code", "name", "continent_name"}
}

// T return metadata info for table 'countries'
func (*Country) T() *__tbl_countries {
	return &_tbl_countries
}

// TableName return table name
func (Country) TableName() string {
	return "countries"
}

/*
Generated by dbml-go
    version: v1.0.0
    timestamp: 2023-02-07 11:02:21.80465651 +0000 UTC m=+0.016955085
*/
