package model

// ProductsStatus is generated type for enum 'products_status'
type ProductsStatus string

const (
	OutOfStock ProductsStatus = "out_of_stock"
	InStock    ProductsStatus = "in_stock"
	RunningLow ProductsStatus = "running_low" // less than 20
)

/*
Generated by dbml-go
    version: v1.0.0
    timestamp: 2023-02-10 14:57:53.345129168 +0000 UTC m=+0.003109501
*/
