// Code generated by dbml-gen-go-model. DO NOT EDIT.
// Supported by duythinht@2020
package model

// ProductsStatus is generated type for enum 'products_status'
type ProductsStatus int

const (
	_ ProductsStatus = iota
	OutOfStock
	InStock
	RunningLow // less than 20
)
