package model

import "time"

// User is generated type for table 'users'
type User struct {
	ID          int       `db:"id" json:"id" mapstructure:"id"`
	FullName    string    `db:"full_name" json:"full_name" mapstructure:"full_name"`
	CreatedAt   time.Time `db:"created_at" json:"created_at" mapstructure:"created_at"`
	CountryCode int       `db:"country_code" json:"country_code" mapstructure:"country_code"`
	Type        int       `db:"type" json:"type" mapstructure:"type"`
	Note        int       `db:"note" json:"note" mapstructure:"note"`
}

// table 'users' columns list struct
type __tbl_users_columns struct {
	ID          string
	FullName    string
	CreatedAt   string
	CountryCode string
	Type        string
	Note        string
}

// table 'users' metadata struct
type __tbl_users struct {
	Name    string
	Columns __tbl_users_columns
}

// table 'users' metadata info
var _tbl_users = __tbl_users{
	Columns: __tbl_users_columns{
		CountryCode: "country_code",
		CreatedAt:   "created_at",
		FullName:    "full_name",
		ID:          "id",
		Note:        "note",
		Type:        "type",
	},
	Name: "users",
}

// GetColumns return list columns name for table 'users'
func (*__tbl_users) GetColumns() []string {
	return []string{"id", "full_name", "created_at", "country_code", "type", "note"}
}

// T return metadata info for table 'users'
func (*User) T() *__tbl_users {
	return &_tbl_users
}

// TableName return table name
func (User) TableName() string {
	return "users"
}

/*
Generated by dbml-go
    version: v1.0.0
    timestamp: 2023-02-01 16:21:33.957979336 +0000 UTC m=+0.006117417
*/
